"""Costanti per Mia Config."""

DOMAIN = "mia_config"
VERSION = "2.2.0"
DEFAULT_NAME = "Mia Config"
DEFAULT_SCAN_INTERVAL = 60
DEFAULT_LOOKAHEAD_HOURS = 168
DEFAULT_LOOKBACK_HOURS = 24
DEFAULT_CLEANUP_DAYS = 180
DEFAULT_HISTORY_RETENTION_DAYS = 730
DEFAULT_MAX_HISTORY_PER_NAME = 100
DEFAULT_MIN_HISTORY_PER_NAME = 10
